Signing_Off/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),

]

home/urls.py
from django.contrib import admin
from . import views
from django.urls import path,include
app_name = 'home'
urlpatterns = [
    path('',views.home, name='home'),
    path('about', views.about, name='about'),
    path('signup', views.signup, name='signup'),
]

home/models.py
from django.db import models


class College(models.Model):
    name = models.CharField(max_length=100, null=False, blank=False)
    college_email = models.CharField(max_length=300, null=False, blank=False)
    form_donate = models.URLField(max_length=300, null=False, blank=False)
    form_receive = models.URLField(max_length=300, null=False, blank=False)
    college_ext = models.CharField(max_length=20, null=False, blank=False)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

home/forms.py
from django import forms
from .models import College


class UserForm(forms.Form):
    college_name = forms.ChoiceField(choices=[])
    email = forms.EmailField(max_length=200, required=True)

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.fields['college_name'].choices = [(x.name,x.name) for x in College.objects.all()]

home/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from Signing_Off.settings import EMAIL_HOST_USER
from .models import College
from .forms import UserForm
from django.core.mail import send_mail, BadHeaderError


def home(request):
    context = {}
    messages.success(request,"Hii")
    return render(request, 'home/home.html', context)


def about(request):
    context = {}
    return render(request, 'home/About.html', context)


options = [x.name for x in College.objects.all()]


def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        print(form)
        if form.is_valid():
            print('valid form')
            college = College.objects.all().filter(name=form.cleaned_data.get('college_name'))[0]
            required_email_ext = college.college_ext
            email = form.cleaned_data.get('email')
            email_ext = email.split('@')[1]
            if required_email_ext == email_ext:
                subject = "Subject"
                if form.cleaned_data.get('enquiry') == 0:
                    form_link = str(college.form_receive)
                else:
                    form_link = str(college.form_donate)
                message = "Here's a form : " + form_link
                to_email = [str(email)]
                print(to_email)
                try:
                    send_mail(subject, message,str(EMAIL_HOST_USER), to_email, fail_silently=False)
                except BadHeaderError:
                    template = 'home/signup.html'
                    context = {
                        'form': form,
                        'errors': 'Invalid header found.',
                        'options': options
                    }
                    return render(request, template, context)
                messages.success(request,'A link is sent to your email!')
                return redirect('home:home')
            else:
                template = 'home/signup.html'
                context = {
                    'form': form,
                    'errors': "This email doesn't belong to " + college.name,
                    'options': options
                }
                return render(request, template, context)
        else:
            template = 'home/signup.html'
            form = UserForm()
            context = {
                'form': form,
                'options': options,
                'errors': 'Invalid form'
            }
            return render(request, template, context)

    template = 'home/signup.html'
    form = UserForm()
    context = {
        'form': form,
        'options': options,
        'errors': ''
    }
    return render(request, template, context)

home/templates/home/About.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}


<div class="content">


      <div class="container">
          <div class="container-2">
        <h1 >About Signing off</h1>
              <br><br>
              <p>Every year hundreds of students pack their things up with heavy hearts, take their degrees and say goodbye to the institute they once called home. While they try to take as many memories with them to their new life, there are some things that they have to leave behind. The bicycles they used for their daily commute, mattresses they used to sleep in, their old textbooks which they heavily read from when exams neared and many other uncountable things.</p>
            <br> <p> The bicycles left behind with no one to ride on or take care of, catch rust in the heavy rain and idleness of college. Every once in awhile, we see a cleaning drive to collect these old bicycles that have slowly turned into junk. Why did we allow them to fade away this way? Can they not help the new students, with new hopes and dreams, make new memories again?</p>
          <br><p>Signing off is a non-profit initiative that enables the seniors to pass on certain feasible objects like cycles, mattresses, and curtains to their juniors. Not only this, but they also get to attach a special message on custom-designed stickers for each item. Perhaps something that they would like to say to their junior selves? We collect their things, store them in a safe place and with the beginning of a new year, give them to those who need them.</p>
             <br><p> Simple idea, right? But look at how it impacts a freshman's life. Not only do they receive something they need, but also a treasured secret message that helps them connect to the ones who took the same journey they are about to embark upon.</p>
            <br><br>
      </div>
          </div>
</div>
{% endblock %}

home/templates/home/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->


    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'home/main.css' %}">




    {% if title %}
        <title>Signing Off!{{ title }} </title>
    {% else %}
        <title> Signing Off! </title>
    {% endif %}
</head>
<body>

<header class="header-basic-light">

    <div class="header-limiter">

        <h1><a href="{% url 'home:home' %}"> Signing off</a></h1>

        <nav>
            <a href="{% url 'home:about' %}">About the initiative</a>
            <a href="#">FAQ</a>
            <a class="btn3" href="{% url 'home:signup' %}">Sign Up</a>

        </nav>
    </div>
</header>
<div class="container">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible show text-center" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {%  endfor %}
{% endif %}
</div>
{% block content %}
{% endblock %}

<footer>
    <!-- Footer main -->
    <section class="ft-main">
        <div class="container-1 ">
            <p>Signing off is an initiative to pass on feasible objects to the newbies who need them, along with
                messages from the seniors who once walked the same road they are about to tread on. We collect bicycles
                and mattresses from the graduating seniors and pass them on to the incoming batch of juniors with the
                help of the Welfare Board, IIT Guwahati.

            </p>
            <p>Simple idea, right? But look how it impacts a freshman's life. We nudge them onto this beautiful journey,
                with new aspirations, new dreams but some old and cherished memories.</p>

            <h1>Excited to organise this in your college?</h1>


            <div class="con" align="center">
                <br>
                <a class="btn" href="">Join Us</a>

                <p> Connect with us on social media accounts</p>
                <p style="font-size: 14px;
line-height: 16px;">Made with <3 by team Signing off © Copyright 2019</p>
            </div>

        </div>


    </section>

    <!-- Footer social -->


    <!-- Footer legal -->

</footer>
</body>
</html>

home/templates/home/home.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}



    <div class="content">
        <div class="container">


            <div class="row">
                <div class="col-xs-6 ">
                    <br><br>
                    <h1 class="myc">Signing off?
                        <span style="display: block;">Leave behind some memories</span></h1>

                    <h4 class="myc1"> An inititative to pass on feasible objects from graduating batches to juniors</h4>
                    <div class="con">
                        <br>
                        <a class="btn1" href={% url 'home:signup' %}>Sign Up</a>


                    </div>
                </div>
                <div class="col-xs-6"><img class="img-responsive" src="{% static 'images/Group_1.png' %}"></div>


            </div>
            <div class="con2" align="center">
                <h1 class="head">How it works</h1>
                <div class="rectangle"></div>

            </div>

            <div class="row r">

                <div class="col-xs-6 c"><img class="myimg" src="{% static 'images/Frame8.png' %}" width="79"
                                             height="76">
                    <h1 class="myc">Sign up</h1>


                    <h4 class="myc1_2"> Start by filling the form and telling us what you wish to donate</h4>
                </div>


                <div class="col-xs-6"><img class="img-responsive" src="{% static 'images/image2.png' %}"></div>


            </div>
            <div class="row r ">


                <div class="col-xs-6"><img class="img-responsive" src="{% static 'images/image1.png' %}"></div>
                <div class="col-xs-6  c"><img class="myimg" src="{% static 'images/Frame7.png' %}" width="79"
                                              height="76">
                    <h1 class="myc">Customise</h1>


                    <h4 class="myc1_2"> Collect customised stickers and pins to write your messages</h4>
                </div>


            </div>
            <div class="row r">

                <div class="col-xs-6 c "><img class="myimg" src="{% static 'images/Frame6.png' %}" width="79"
                                              height="76">
                    <h1 class="myc">Donate</h1>


                    <h4 class="myc1_2"> Drop your things with our volunteers before leaving and you're done </h4>
                </div>


                <div class="col-xs-6"><img class="img-responsive" src="{% static 'images/image3.png' %}"></div>


            </div>


            <br><br><br>


        </div>
    </div>

{% endblock %}

home/templates/home/signup.html
{% extends "home/base.html" %}
{% load static %}
{% block content %}
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 ">

                <div class="form-error">
                    <ul>
                        {% for error in form.errors %}
                            <li>
                                {{ error }}
                            </li>
                        {% endfor %}
                    {% if errors %}
                        <li>
                        {{errors}}
                    </li>
                    {% endif %}
                    </ul>
                </div>

                <form method="POST" class="login100-form" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="center radio-container">
                        <label for="receive">
                            <input type="radio" id="receive" name="enquiry" value=0 required checked/>
                            <div class="front-end box">
                                <span>Receive</span>
                            </div>
                        </label>

                        <label for="donate">
                            <input type="radio" id="donate" name="enquiry" value=1/>
                            <div class="back-end box">
                                <span>Donate </span>
                            </div>
                        </label>

                    </div>
                    <br>

                    <br>
                    <span class="login1">Choose Your Institute</span>
                    <br>
                    <div class="wrap-input100 " data-validate="Institute name is is required">
                        <select id="{{ form.college_name.id_for_label }}" name="{{ form.college_name.html_name }}"
                                class="input100" required>
                            {% for option in options %}
                                <option value="{{ option }}">{{ option }}</option>
                            {% endfor %}
                        </select>

                    </div>
                    <br>
                    <span class="login1">Your institute mail address</span>

                    <div class="wrap-input100 " data-validate="Email is required">
                        <input class="input100" id="{{ form.email.if_for_label }}" type="email"
                               name="{{ form.email.html_name }}" required
                               value="{{ form.email.value | default_if_none:'' }}"/>
                    </div>
                    <br>
                    <br>
                    <div style="margin: auto; text-align: center">
                        <button class="btn1" type="submit" style="display: inline-block"> Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}